// Generated by CoffeeScript 1.4.0

(function($) {
  "use strict";

  var App, initialize;
  App = {
    init: function() {}
  };
  initialize = function() {
    return App.init();
  };
  return $(initialize);
})(jQuery);
