title: Tom Gordon - frontend web developer in Melbourne, Australia
name: Tom Gordon
role: frontend web development
highlighter: true
subname: Frontend web developer
permalink: /:categories/:day/:month/:year/:title.html
navigation:
    - text: email me
      url: mailto:thomasgordon02@gmail.com
      icon: envelope
      class: js-transform-email
    - text: linked in
      url: http://www.linkedin.com/profile/view?id=46634189&trk=tab_pro
      icon: linkedin
    - text: github
      url: http://github.com/thomas-gordon
      icon: github
    - text: twitter
      url: http://www.twitter.com/tomgwebdev
      icon: twitter
    - text: resume
      url: https://docs.google.com/document/d/1Rw7b9PkSPXlfwEWWLziUkVCC5CsWF0Pmbv1R0jZssf8/
      icon: book
    - text: medium
      url: https://medium.com/@tomgwebdev
      icon: pencil
exclude: ['bower_components', 'node_modules', 'coffee', 'scss']


