name: Tom Gordon
pygments: true
subname: Web developer
permalink: /:categories/:day/:month/:year/:title.html
comments: true
navigation:
    - text: Blog
      url: /index.html
    - text: Work
      title: Letters home from abroad
      url: /work.html